baseurl = "https://salamachinas.net"
title = "Salamachinas"
theme = "own"
author = "Aurimas Salamachinas"

[params]
author = "Aurimas Salamachinas"
description = "Aurimas Salamachinas personal website"
keywords = "Gopher,Technical diver,Salamachinas"
since = 2014
info = "Gopher and Technical diver"
gravatar = "a.salamachinas@gmail.com"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github"
weight = 1
url = "https://github.com/salamachinas/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter"
weight = 2
url = "https://twitter.com/salamachinas/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin-in"
weight = 3
url = "https://www.linkedin.com/in/salamachinas/"

[params.googleTagManager]
id = "G-L8S8LPL1KN"

[params.cookiebot]
cbid = "46bf531f-f819-4880-b4c2-d3da4a5cc1b8"
